language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
  - "5.0.0"
before_install: npm install -g grunt-cli
install: npm install
sudo: false
after_success:
  npm run-script test
cache:
  directories:
    - node_modules
notifications:
  slack: bottry:qGLlvCPcGHJp6kcmmPuCcHGd
  webhooks:
    - http://ci-alarm.herokuapp.com/
